// The elements registry (one querySelector pass at boot) plus tiny shared DOM render helpers.

const elements = {
  connectionStatus: document.querySelector("#connectionStatus"),
  deviceFacts: document.querySelector("#deviceFacts"),
  keyReadout: document.querySelector("#keyReadout"),
  storageMediaStatus: document.querySelector("#storageMediaStatus"),
  probeAudio: document.querySelector("#probeAudio"),
  clientIdInput: document.querySelector("#clientIdInput"),
  spotifyFacts: document.querySelector("#spotifyFacts"),
  log: document.querySelector("#log"),
  authPanel: document.querySelector("#authPanel"),
  pairCard: document.querySelector("#pairCard"),
  pairQr: document.querySelector("#pairQr"),
  pairCode: document.querySelector("#pairCode"),
  pairUrl: document.querySelector("#pairUrl"),
  deviceStatus: document.querySelector("#deviceStatus"),
  keyStatus: document.querySelector("#keyStatus"),
  newReleasesShelf: document.querySelector("#newReleasesShelf"),
  playlistsHomeShelf: document.querySelector("#playlistsHomeShelf"),
  topShelf: document.querySelector("#topShelf"),
  recentShelf: document.querySelector("#recentShelf"),
  signedOutHero: document.querySelector("#signedOutHero"),
  homeShelves: document.querySelector("#homeShelves"),
  playlistShelf: document.querySelector("#playlistShelf"),
  libraryAlbumsShelf: document.querySelector("#libraryAlbumsShelf"),
  libraryTracksShelf: document.querySelector("#libraryTracksShelf"),
  devicesGrid: document.querySelector("#devicesGrid"),
  nowArtwork: document.querySelector("#nowArtwork"),
  nowBackdrop: document.querySelector("#nowBackdrop"),
  nowContext: document.querySelector("#nowContext"),
  nowTitle: document.querySelector("#nowTitle"),
  nowArtist: document.querySelector("#nowArtist"),
  progressFill: document.querySelector("#progressFill"),
  positionText: document.querySelector("#positionText"),
  durationText: document.querySelector("#durationText"),
  ambientBg: document.querySelector("#ambientBg"),
  ambientStage: document.querySelector("#ambientStage"),
  ambientModeLabel: document.querySelector("#ambientModeLabel"),
  ambientTitle: document.querySelector("#ambientTitle"),
  ambientSubtitle: document.querySelector("#ambientSubtitle"),
  ambientRoomArt: document.querySelector("#ambientRoomArt"),
  ambientRoomArtB: document.querySelector("#ambientRoomArtB"),
  ambientRoomArtFrame: document.querySelector("#ambientRoomArtFrame"),
  sceneNp: document.querySelector("#sceneNp"),
  sceneNpArt: document.querySelector("#sceneNpArt"),
  sceneNpTitle: document.querySelector("#sceneNpTitle"),
  sceneNpArtist: document.querySelector("#sceneNpArtist"),
  sceneNpProgressFill: document.querySelector("#sceneNpProgressFill"),
  sceneNpTime: document.querySelector("#sceneNpTime"),
  sceneNpStatus: document.querySelector("#sceneNpStatus"),
  ambientVisualizerCanvas: document.querySelector("#ambientVisualizerCanvas"),
  ambientVisualizerArt: document.querySelector("#ambientVisualizerArt"),
  ambientScreensaver: document.querySelector("#ambientScreensaver"),
  sceneSky: document.querySelector("#sceneSky"),
  sceneCanvas: document.querySelector("#sceneCanvas"),
  sceneFgCanvas: document.querySelector("#sceneFgCanvas"),
  sceneLayerFar: document.querySelector("#sceneLayerFar"),
  sceneLayerMid: document.querySelector("#sceneLayerMid"),
  sceneLayerNear: document.querySelector("#sceneLayerNear"),
  sceneMist: document.querySelector("#sceneMist"),
  ambientSceneControls: document.querySelector("#ambientSceneControls"),
  sceneNatureBtn: document.querySelector("#sceneNatureBtn"),
  sceneSkylineBtn: document.querySelector("#sceneSkylineBtn"),
  sceneSkipBtn: document.querySelector("#sceneSkipBtn"),
  ambientControls: document.querySelector("#ambientControls"),
  ambientProgressFill: document.querySelector("#ambientProgressFill"),
  ambientProgressTime: document.querySelector("#ambientProgressTime"),
  toastStack: document.querySelector("#toastStack"),
  npPill: document.querySelector("#npPill"),
  npPillArt: document.querySelector("#npPillArt"),
  npPillTitle: document.querySelector("#npPillTitle"),
  npPillArtist: document.querySelector("#npPillArtist"),
  npPillProgressFill: document.querySelector("#npPillProgressFill"),
  npPillTime: document.querySelector("#npPillTime"),
  npPillPlayBtn: document.querySelector("#npPillPlayBtn"),
  collectionBackdrop: document.querySelector("#collectionBackdrop"),
  collectionArt: document.querySelector("#collectionArt"),
  collectionKind: document.querySelector("#collectionKind"),
  collectionTitle: document.querySelector("#collectionTitle"),
  collectionMeta: document.querySelector("#collectionMeta"),
  collectionShuffleBtn: document.querySelector("#collectionShuffleBtn"),
  collectionSaveBtn: document.querySelector("#collectionSaveBtn"),
  collectionTracks: document.querySelector("#collectionTracks"),
  searchKeys: document.querySelector("#searchKeys"),
  searchQueryText: document.querySelector("#searchQueryText"),
  searchHint: document.querySelector("#searchHint"),
  searchTracksShelf: document.querySelector("#searchTracksShelf"),
  searchArtistsShelf: document.querySelector("#searchArtistsShelf"),
  searchAlbumsShelf: document.querySelector("#searchAlbumsShelf"),
  searchPlaylistsShelf: document.querySelector("#searchPlaylistsShelf"),
  artistBackdrop: document.querySelector("#artistBackdrop"),
  artistArt: document.querySelector("#artistArt"),
  artistTitle: document.querySelector("#artistTitle"),
  artistMeta: document.querySelector("#artistMeta"),
  artistTopTracks: document.querySelector("#artistTopTracks"),
  artistAlbumsShelf: document.querySelector("#artistAlbumsShelf"),
  viewArtist: document.querySelector("#view-artist"),
  diagnostics: document.querySelector("#diagnostics"),
  toggleDebugView: document.querySelector("#toggleDebugView"),
  toggleDebugState: document.querySelector("#toggleDebugState"),
  viewAmbient: document.querySelector("#view-ambient"),
  viewNow: document.querySelector("#view-now"),
  viewCollection: document.querySelector("#view-collection"),
  navRail: document.querySelector("#navRail"),
  phonePairScreen: document.querySelector("#phonePairScreen"),
  phonePairCode: document.querySelector("#phonePairCode"),
  phonePairErrorMessage: document.querySelector("#phonePairErrorMessage"),
  phonePairSuccessMessage: document.querySelector("#phonePairSuccessMessage"),
  exitDialog: document.querySelector("#exitDialog"),
  exitDialogCancel: document.querySelector("#exitDialogCancel"),
  exitDialogConfirm: document.querySelector("#exitDialogConfirm"),
  queueDrawer: document.querySelector("#queueDrawer"),
  queueList: document.querySelector("#queueList"),
  trackMenu: document.querySelector("#trackMenu"),
  trackMenuArt: document.querySelector("#trackMenuArt"),
  trackMenuTitle: document.querySelector("#trackMenuTitle"),
  trackMenuArtist: document.querySelector("#trackMenuArtist"),
  trackMenuActions: document.querySelector("#trackMenuActions"),
  upNext: document.querySelector("#upNext"),
  upNextArt: document.querySelector("#upNextArt"),
  upNextTitle: document.querySelector("#upNextTitle"),
  upNextArtist: document.querySelector("#upNextArtist"),
};

function renderFacts(container, facts) {
  if (!container) return;
  container.replaceChildren();
  for (const [key, value] of Object.entries(facts)) {
    const dt = document.createElement("dt");
    const dd = document.createElement("dd");
    dt.textContent = key;
    dd.textContent = value;
    container.append(dt, dd);
  }
}

function emptyState(message) {
  const div = document.createElement("div");
  div.className = "card card--placeholder";
  div.textContent = message;
  return div;
}

export { elements, emptyState, renderFacts };
